import { StyleSheet } from 'react-native';

import { colors } from '../theme';

export const formatMinutes = (minutes: number) => {
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text, textTransform: 'lowercase' },
  iconButton: { padding: 6, borderRadius: 999 },
  scroll: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 120, gap: 14 },
  body: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
  centeredPage: { flex: 1, justifyContent: 'center', paddingHorizontal: 20, gap: 18 },
  heroTitle: { fontSize: 34, fontWeight: '700', color: colors.text, textAlign: 'center', textTransform: 'lowercase' },
  heroTitleSmall: { fontSize: 28, fontWeight: '700', color: colors.text, textTransform: 'lowercase' },
  heroSubtitle: { fontSize: 16, color: colors.textMuted, textAlign: 'center', textTransform: 'lowercase' },
  form: { gap: 12 },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: colors.text,
    marginTop: 10,
  },
  textArea: { minHeight: 120, textAlignVertical: 'top' },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 96,
    marginTop: 10,
  },
  buttonSecondary: { backgroundColor: colors.surfaceAlt },
  buttonText: { color: '#fff', fontWeight: '700', textTransform: 'lowercase' },
  buttonTextSecondary: { color: colors.text },
  inlineText: { color: colors.textMuted, textAlign: 'center', textTransform: 'lowercase' },
  linkText: { color: colors.primary, fontWeight: '700' },
  mailIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' },
  codeRow: { flexDirection: 'row', gap: 8, justifyContent: 'center' },
  codeInput: { width: 46, height: 58, borderRadius: 14, borderWidth: 2, borderColor: colors.border, backgroundColor: '#fff', textAlign: 'center', fontSize: 22, color: colors.text },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 16, gap: 10 },
  cardTitle: { fontSize: 16, fontWeight: '700', color: colors.text, textTransform: 'lowercase' },
  cardText: { fontSize: 13, color: colors.textMuted, textTransform: 'lowercase', lineHeight: 18 },
  sectionLabel: { fontSize: 14, fontWeight: '700', color: colors.textMuted, textTransform: 'lowercase', marginBottom: 2 },
  rowGap: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  tintIcon: { backgroundColor: colors.primary, padding: 10, borderRadius: 12, overflow: 'hidden' },
  contactCard: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, backgroundColor: colors.surfaceAlt, borderRadius: 20 },
  contactCardActive: { backgroundColor: colors.primary },
  contactName: { fontSize: 15, fontWeight: '700', color: colors.text, textTransform: 'lowercase' },
  contactPhone: { fontSize: 12, color: colors.textMuted },
  contactNameActive: { color: '#fff' },
  contactPhoneActive: { color: 'rgba(255,255,255,0.8)' },
  avatar: { width: 48, height: 48, borderRadius: 24 },
  flexOne: { flex: 1 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(61,57,53,0.4)', justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: colors.surface, borderRadius: 28, padding: 18, gap: 10 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: colors.text, textTransform: 'lowercase' },
  optionRow: { padding: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 20 },
  optionRowActive: { borderColor: colors.primary, backgroundColor: '#f5ebe4' },
  optionRowText: { color: colors.text, fontWeight: '700', textTransform: 'lowercase' },
  selectAppsCard: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, backgroundColor: colors.surface, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.borderMuted, borderRadius: 22 },
  listCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, padding: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 22, marginTop: 2 },
  segmented: { flexDirection: 'row', backgroundColor: colors.surfaceAlt, borderRadius: 999, padding: 4, gap: 4 },
  segment: { flex: 1, paddingVertical: 10, borderRadius: 999, alignItems: 'center' },
  segmentActive: { backgroundColor: colors.primary },
  segmentText: { color: colors.textMuted, fontWeight: '700', textTransform: 'lowercase' },
  segmentTextActive: { color: '#fff' },
  promoCard: { backgroundColor: colors.primary, borderRadius: 22, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 },
  promoTitle: { color: '#fff', fontWeight: '700', textTransform: 'lowercase' },
  promoSubtitle: { color: 'rgba(255,255,255,0.85)', fontSize: 12, textTransform: 'lowercase' },
  horizontalList: { gap: 16, paddingRight: 16 },
  partnerItem: { alignItems: 'center', width: 74 },
  avatarLarge: { width: 64, height: 64, borderRadius: 32 },
  partnerText: { marginTop: 8, color: colors.textMuted, fontSize: 12, textTransform: 'lowercase' },
  addBubble: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.surfaceAlt, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.borderMuted, alignItems: 'center', justifyContent: 'center' },
  requestImage: { width: '100%', height: 120, borderRadius: 14, marginBottom: 8 },
  actionRow: { flexDirection: 'row', gap: 10 },
  badge: { minWidth: 18, height: 18, borderRadius: 9, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  badgeTextPlain: { fontSize: 12, fontWeight: '700', color: colors.textSoft, textTransform: 'lowercase' },
  accepted: { color: colors.success },
  subList: { paddingLeft: 14, gap: 8 },
  subListCard: { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 14 },
  planCard: { flexDirection: 'row', gap: 12, borderWidth: 2, borderColor: colors.border, borderRadius: 20, padding: 14 },
  planCardActive: { borderColor: colors.primary, backgroundColor: '#f5ebe4' },
  radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1, borderColor: colors.borderMuted, alignItems: 'center', justifyContent: 'center' },
  radioActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  centerBlock: { alignItems: 'center', gap: 10, paddingVertical: 10 },
  tokenCircle: { width: 120, height: 120, borderRadius: 60, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  bigNumber: { fontSize: 44, fontWeight: '700', color: colors.text },
  qrPlaceholder: { height: 180, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 12 },
  searchInput: { flex: 1, color: colors.text, padding: 0 },
  topActions: { flexDirection: 'row', gap: 8 },
  bigStat: { fontSize: 28, fontWeight: '700', color: colors.textMuted },
  dockWrap: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingBottom: 20 },
  dock: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: 'rgba(245,243,240,0.97)', borderRadius: 24, borderWidth: 1, borderColor: 'rgba(255,255,255,0.5)', paddingVertical: 12 },
  dockItem: { paddingVertical: 6, paddingHorizontal: 8 },
  dockText: { color: colors.textMuted, fontSize: 12, fontWeight: '700', textTransform: 'lowercase' },
  contactRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerMiniButton: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#ebe8e3', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 18 },
  headerMiniButtonText: { color: colors.textMuted, fontSize: 12, fontWeight: '600', textTransform: 'lowercase' },
  friendListRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, paddingHorizontal: 8, borderRadius: 18 },
  friendAvatarWrap: { position: 'relative' },
  friendBadge: { position: 'absolute', top: -2, right: -2, minWidth: 18, height: 18, borderRadius: 9, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  friendListName: { flex: 1, color: colors.text, fontSize: 16, textTransform: 'lowercase' },
  largeRowCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 16 },
  scanBubble: { width: 48, height: 48, borderRadius: 16, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  largeRowTitle: { color: colors.text, fontSize: 16, fontWeight: '400', textTransform: 'lowercase' },
  largeRowSubtitle: { color: colors.textMuted, fontSize: 12, marginTop: 4, textTransform: 'lowercase' },
  inlineChip: { backgroundColor: '#ebe8e3', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 18 },
  inlineChipText: { color: colors.textMuted, fontSize: 13, textTransform: 'lowercase' },
  contactListCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 12, marginTop: 8 },
  addPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.primary, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10 },
  addPillDisabled: { backgroundColor: '#ebe8e3' },
  addPillText: { color: '#fff', fontSize: 13, textTransform: 'lowercase' },
  addPillTextDisabled: { color: colors.textSoft },
  userIdInput: { fontFamily: 'monospace', letterSpacing: 2, textTransform: 'uppercase' as const },
  fullButton: { backgroundColor: colors.primary, paddingVertical: 14, borderRadius: 18, alignItems: 'center', marginTop: 8 },
  fullButtonDisabled: { backgroundColor: '#ebe8e3' },
  fullButtonText: { color: '#fff', fontWeight: '700', textTransform: 'lowercase' },
  fullButtonTextDisabled: { color: colors.textSoft },
  membershipModalCard: { backgroundColor: colors.surface, borderRadius: 28, padding: 18, gap: 12, maxHeight: '90%' },
  planPrice: { color: colors.text, fontSize: 24, fontWeight: '700', marginTop: 10 },
  billingWrap: { gap: 10, marginTop: 4 },
  billingLabel: { color: colors.textMuted, fontSize: 13, fontWeight: '600', textTransform: 'lowercase' },
  billingCard: { flexDirection: 'row', gap: 12, borderWidth: 2, borderColor: colors.border, borderRadius: 20, padding: 14 },
  billingPrice: { color: colors.text, fontSize: 18, fontWeight: '700' },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#fff' },
  faqSection: { marginTop: 10, gap: 8 },
  faqCategory: { color: colors.textSoft, fontSize: 12, fontWeight: '600', textTransform: 'lowercase', paddingHorizontal: 8 },
  faqCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 16, gap: 10 },
  faqQuestion: { flex: 1, color: colors.text, fontSize: 15, fontWeight: '600', paddingRight: 12, textTransform: 'lowercase' },
  faqAnswer: { color: colors.textMuted, fontSize: 13, lineHeight: 18, textTransform: 'lowercase' },
  faqEmpty: { alignItems: 'center', paddingVertical: 40, gap: 6 },
  faqEmptySub: { color: colors.textSoft, fontSize: 12, textTransform: 'lowercase' },
});

